name: Cleardown Infrastructure
on:
  workflow_call:
    inputs:
      github_environment:
        description: "Defines the Github environment in which to pull environment variables from"
        required: true
        type: string
      #deployment_workspace:
      #  description: 'Name of the terraform workspace to tear down the service infrastructure'
      #  required: false
      #  type: string
      branch_name:
        description: "Name of the branch used to derive tf version and workspace"
        required: true
        default: 'not-set'
        type: string

jobs:
  echo-workflow-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: echo workflow inputs
        run: |
          echo "github environment: ${{ inputs.github_environment }}"
          echo "branch_name: ${{ inputs.branch_name }}"
  derive-tf-versions:
    uses: ./.github/workflows/derive-tf-version.yaml
    # TODO
  get-metadata:
    runs-on: ubuntu-latest
    outputs:
      build_datetime: ${{ steps.metadata.outputs.build_datetime }}
      build_timestamp: ${{ steps.metadata.outputs.build_timestamp }}
      build_epoch: ${{ steps.metadata.outputs.build_epoch }}
    steps:
      - id: metadata
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "triggering action: ${{ github.event_name }}"
          echo "ref type: ${{ github.ref_type }}"
          echo "triggering reference: ${{ github.ref_name }}"
          echo "github.event.ref : ${{ github.event.ref }}"
          echo "github.head_ref" ${{github.head_ref }}
          echo "username of user triggering the workflow: ${{ github.actor }}"
  derive-workspace:
    uses: ./.github/workflows/derive-terraform-workspace-from-branch-name.yaml
    with:
      branch_name: ${{ inputs.branch_name }}

  destroy-application-infrastructure:
    needs:
      [
        derive-tf-versions,
        derive-workspace
      ]
    uses: ./.github/workflows/action-infrastructure-stack.yaml
    with:
      github_environment: ${{ inputs.github_environment }}
      stack: application
      action: destroy
      deployment_workspace: ${{needs.derive-workspace.outputs.workspace}}
      tf_vers: ${{needs.derive-tf-versions.outputs.maxVersion}}
    secrets: inherit
  cleardown-terraform-state:
    needs:
      [
        destroy-application-infrastructure,
        derive-workspace
      ]
    uses: ./.github/workflows/cleardown-terraform-state.yaml
    with:
      github_environment: ${{ inputs.github_environment }}
      deployment_workspace: ${{needs.derive-workspace.outputs.workspace}}
    secrets: inherit
