name: CI/CD Develop Pipeline

on:
  push:
    branches:
      - main
      - 'task/*'

jobs:
  get-metadata:
    runs-on: ubuntu-latest
    outputs:
      build_datetime: ${{ steps.metadata.outputs.build_datetime }}
      build_timestamp: ${{ steps.metadata.outputs.build_timestamp }}
      build_epoch: ${{ steps.metadata.outputs.build_epoch }}
    steps:
      - id: metadata
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "triggering action: ${{ github.event_name }}"
          echo "ref type: ${{ github.ref_type }}"
          echo "triggering reference: ${{ github.ref_name }}"
  scan-secrets:
    uses: ./.github/workflows/scan-secrets.yaml
  check-file-format:
    uses: ./.github/workflows/check-file-format.yaml
  check-markdown-format:
    uses: ./.github/workflows/check-markdown-format.yaml
  check-terraform-format:
      uses: ./.github/workflows/check-terraform-format.yaml
  validate-terraform:
    name: Validate terraform code
    uses: ./.github/workflows/validate-terraform.yaml
    with:
      ENV: dev
    secrets: inherit
  check-python-black-format:
      uses: ./.github/workflows/check-python-black-format.yaml
  check-python-flake-rules:
      uses: ./.github/workflows/check-python-flake-rules.yaml
  cloc-repository:
    uses: ./.github/workflows/cloc-repository.yaml
  unit-tests:
    needs:
      [
        get-metadata,
        scan-secrets,
        check-file-format,
        check-markdown-format,
        check-terraform-format,
        check-python-black-format,
        check-python-flake-rules,
        cloc-repository,
      ]
    name: Run unit test
    uses: ./.github/workflows/unit-test.yaml
    with:
      github_environment: dev
    secrets: inherit
  # unit-test:
  #   runs-on: ubuntu-latest
  #   # timeout-minutes: 10
  #   # steps:
  #   #   - uses: actions/checkout@v4
  #   #   - name: List Variables
  #   #     run: |
  #   #       export BUILD_DATETIME="${{ needs.get-metadata.outputs.build_datetime }}"
  #   #       export BUILD_TIMESTAMP="${{ needs.get-metadata.outputs.build_timestamp }}"
  #   #       export BUILD_EPOCH="${{ needs.get-metadata.outputs.build_epoch }}"
  #   #       echo "Unit tests invoked"
  #     # - name: Run Tests
  #   uses: ./.github/workflows/unit-test.yaml
  #   with:
  #     github_environment: dev
  #   secrets: inherit
  orchestrate-terraform:
      needs:
        [
          unit-tests,
          validate-terraform,
        ]
      uses: ./.github/workflows/orchestrate-terraform.yaml
      with:
        github_environment: dev
      secrets: inherit
