name: CI/CD Test Deployment

on:
  push:
    tags:
      - '[A-Z][A-Z]-[0-9][0-9]?[0-9]?[0-9]?-test-[0-9][0-9]?'

env:
  GITHUB_ENVIRONMENT: test

jobs:
  get-metadata:
    runs-on: ubuntu-latest
    outputs:
      build_datetime: ${{ steps.metadata.outputs.build_datetime }}
      build_timestamp: ${{ steps.metadata.outputs.build_timestamp }}
      build_epoch: ${{ steps.metadata.outputs.build_epoch }}
    steps:
      - id: metadata
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "triggering action: ${{ github.event_name }}"
          echo "ref type: ${{ github.ref_type }}"
          echo "triggering reference: ${{ github.ref_name }}"
  deploy-application-infrastructure:
    uses: ./.github/workflows/reusable-workflows/deploy-application-infrastructure.yaml
    with:
      github_environment: $GITHUB_ENVIRONMENT
    secrets: inherit
  deploy-development-support-tools:
    if: ${{ github.ref_name=='task/DR-406_Athena_tf_stack123' }}
    uses: ./.github/workflows/reusable-workflows/deploy-development-support-tools.yaml
    with:
      github_environment: $GITHUB_ENVIRONMENT
    secrets: inherit
  integration-test:
    runs-on: ubuntu-latest
    needs:
      [
        get-metadata,
        orchestrate-terraform,
      ]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: List Variables
        run: |
          export BUILD_DATETIME="${{ needs.get-metadata.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ needs.get-metadata.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ needs.get-metadata.outputs.build_epoch }}"
          echo "Integration tests invoked"
      # - name: Run Tests ...
      #   run: |
      #     ?
