name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: src/frontend

      - name: Build React app
        run: npm run build
        working-directory: src/frontend

      - name: Extract Workspace Name
        run: |
          WORKSPACE=$(echo ${GITHUB_REF#refs/heads/} | cut -d'/' -f 2)
          echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV
          ISSUE_KEY=$(echo $WORKSPACE | cut -d'-' -f 1)
          echo "ISSUE_KEY=$ISSUE_KEY" >> $GITHUB_ENV

      - name: Get S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          BUCKET_NAME=$(for bucket in $(aws s3api list-buckets --query "Buckets[].Name" --output text)
          do
          bucket_suffix=$(echo $bucket | cut -d'-' -f 5)
                if [ "$bucket_suffix" == "${{ env.ISSUE_KEY }}" ]; then
                  echo $bucket
                  break
                fi
              done)
              echo "S3_BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

          - name: Deploy to S3
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            run: |
              aws s3 cp build/ s3://${{ env.S3_BUCKET_NAME }}/${{ github.ref }} --recursive
            working-directory: src/frontend
