name: Deploy Support Tools

on:
  workflow_call:
    inputs:
      github_environment:
        description: "Defines the Github environment in which to pull environment variables from"
        required: true
        type: string
jobs:
  deploy-support-tools:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/uec-cm-github-runner
          role-session-name: github-pipeline-session
          aws-region: ${{ vars.AWS_REGION }}

      - name: Initialise and Run Support Tools Terraform
        run: |
          export ACTION=apply
          export STACK=support_tools
          export ACCOUNT_TYPE=${{ vars.ACCOUNT_TYPE }}
          export TF_VAR_aws_serverless_applications_repo_url=${{ vars.AWS_SERVERLESS_APPLICATIONS_REPO_URL }}
          export DEPLOYMENT_WORKSPACE=default
          /bin/bash ./scripts/infra-deploy.sh
