name: NPM Unit Tests

on:
  workflow_call:

jobs:
  npm-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
            /bin/bash ./scripts/npm-unit-tests.sh
