name: Orchestrate terraform workflow

on:
  push:
    branches:
      - 'main'

jobs:
    apply-terraform-dos-dev:
      name: Build read-write iam policies for dos dev account
      uses: ./.github/workflows/apply-terraform.yaml
      with:
        ENV: dev
      secrets: inherit
