name: Pipeline Deployment Application Test Environment

on:
  workflow_call:
    inputs:
      git_tag:
        description: "Defines git commit tag to be used for deployment"
        required: true
        type: string

jobs:
  derive-tf-versions:
    name: Derive terraform version
    uses: ./.github/workflows/derive-tf-version.yaml
    with:
      git_ref: ${{ inputs.git_tag }}
  get-metadata:
    name: Get metadata
    runs-on: ubuntu-latest
    outputs:
      build_datetime: ${{ steps.metadata.outputs.build_datetime }}
      build_timestamp: ${{ steps.metadata.outputs.build_timestamp }}
      build_epoch: ${{ steps.metadata.outputs.build_epoch }}
    steps:
      - id: metadata
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "triggering action: ${{ github.event_name }}"
          echo "ref type: ${{ github.ref_type }}"
          echo "triggering git reference: ${{ github.ref_name }}"
          echo "deploying from git tag ${{ inputs.git_tag }}"
  derive-deployment-workspace:
    name: Derive deployment workspace
    runs-on: ubuntu-latest
    outputs:
      deployment_workspace: ${{ steps.derive-workspace-from-tag.outputs.deployment_workspace }}
    steps:
      - id: derive-workspace-from-tag
        name: Extract deployment workspace from git tag
        run: |
            echo "deployment_workspace=$(awk -F- '{print $1}' <<< ${{ inputs.git_tag }})-$(awk -F- '{print $2}' <<< ${{ inputs.git_tag }})" >> $GITHUB_OUTPUT
  deploy-application-infrastructure:
    name: Deploy application infrastructure
    needs:
      [
        derive-tf-versions,
        derive-deployment-workspace,
      ]
    uses: ./.github/workflows/action-infrastructure-stack.yaml
    with:
      github_environment: "test"
      deployment_workspace: ${{ needs.derive-deployment-workspace.outputs.deployment_workspace }}
      stack: application
      action: apply
      tf_vers: ${{needs.derive-tf-versions.outputs.maxVersion}}
      git_ref: ${{ inputs.git_tag }}
    secrets: inherit
  build-and-deploy-react-app-to-s3-bucket:
    name: Build and deploy react app to S3 bucket
    needs: [
      deploy-application-infrastructure,
      derive-deployment-workspace
    ]
    uses: ./.github/workflows/build-and-deploy-react-app.yaml
    with:
      github_environment: test
      deployment_workspace: ${{needs.derive-deployment-workspace.outputs.deployment_workspace}}
    permissions:
      id-token: write
      contents: read
    secrets: inherit
  ui-test:
    needs:
      [
        get-metadata,
        deploy-application-infrastructure,
        build-and-deploy-react-app-to-s3-bucket,
        derive-deployment-workspace
      ]
    name: Run ui tests
    uses: ./.github/workflows/ui-test.yaml
    with:
      github_environment: test
      DEPLOYMENT_WORKSPACE: ${{ needs.derive-deployment-workspace.outputs.deployment_workspace }}
    secrets: inherit
