name: Tag and deploy code to int account
on:
  pull_request:
    types: [ labeled ]

jobs:
  metadata:
    name: "Get Metadata"
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.33
  generate-tag-name:
    name: "Generate Tag Name"
    if: ${{ github.event.label.name == 'Int Ready' }} && startswith(github.head_ref, 'task/')
    needs:
      [
        metadata,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/generate-tag-name.yaml@v0.33
    with:
      workspace: ${{ needs.metadata.outputs.workspace }}
      tag_type: int
      use_commit_hash: "yes"
      commit_hash: ${{ needs.metadata.outputs.artefact_commit_hash }}
  tag-repository:
    name: "Tag Repository"
    needs:
      [
        metadata,
        generate-tag-name,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/tag-repository.yaml@v0.33
    with:
      tag_to_push: ${{ needs.generate-tag-name.outputs.tag_name }}
      tag_overwrite: "yes"
  build-full-application:
    name: Build full application
    needs:
      [
        metadata,
        generate-tag-name,
        tag-repository,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/build-full-application.yaml@v0.33
    with:
      environment: int
      workspace: ${{ needs.metadata.outputs.workspace }}
      triggering_repo: 'uec-cm'
      triggering_repo_commit_hash: ${{ needs.metadata.outputs.artefact_commit_hash }}
      multi_domain: 'true'
    secrets: inherit
