name: Deploy development support tools

on:
  push:
    branches:
      - 'task/DR-406_Athena_tf_stack'
jobs:
  deploy-development-support-tools-dev:
    uses: ./.github/workflows/deploy-support-tools.yaml
    with:
      github_environment: dev
    secrets: inherit
  deploy-development-support-tools-test:
    uses: ./.github/workflows/deploy-support-tools.yaml
    with:
      github_environment: test
    secrets: inherit
