name: Pipeline Cleardown Artefacts

on:
  delete:
    branches:
      - 'task/*'
jobs:
  metadata:
    if: github.event.ref_type == 'branch' && startswith(github.event.ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    name: "Get Metadata"
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.23
  cleardown-artefacts:
    if: github.event.ref_type == 'branch' && startswith(github.event.ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    name: "Cleardown Artefacts"
    needs:
      [
        metadata,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/artefacts-cleardown.yaml
    with:
      environment: dev
      workspace: ${{ needs.metadata.outputs.workspace }}
      artefact_bucket_name: ${{needs.metadata.outputs.artefact_bucket_name}}
    secrets: inherit

  summarise:
    if: github.event.ref_type == 'branch' && startswith(github.event.ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "${{ github.actor }} deleted a task branch..."
          echo "triggering cleardown of infra in dev account relating to ${{ github.ref_type }}: ${{ github.event_ref }}"

  slack-notifications:
    name: Send notification to slack
    needs: [
      cleardown-artefacts,
      summarise,
    ]
    if: always()
    uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@v0.23
    with:
      env: dev
    secrets: inherit
