name: Pipeline Deployment Application Test Environment

on:
  workflow_call:
    inputs:
      environment:
        description: "The name of the environment to build into"
        required: true
        type: string
      workspace:
        description: "The workspace to deploy the service into"
        required: true
        type: string

jobs:
  metadata:
    name: "Get Metadata"
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.36
  deploy-application-infrastructure:
    name: Deploy application infrastructure
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.36
    with:
      environment: ${{ inputs.environment }}
      domain: "uec-cm"
      project: cm
      workspace: ${{ inputs.workspace }}
      stacks: "['application']"
      action: apply
      workflow_timeout: 10
    secrets: inherit

  build-and-push-react-artefacts:
    name: Build react app and push built artefact to s3 bucket
    needs: [
      metadata,
      deploy-application-infrastructure,
    ]
    uses: NHSDigital/uec-dos-management/.github/workflows/build-react-app.yaml@v0.36
    with:
      environment: ${{ inputs.environment }}
      workspace:  ${{ inputs.workspace }}
      domain: uec-cm
      commit_hash: ${{ needs.metadata.outputs.commit_hash }}
      artefact_bucket_name: ${{ needs.metadata.outputs.artefact_bucket_name }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  deploy-react-app:
    name: Retrieve built artefact and deploy to front end s3 bucket
    needs: [
      metadata,
      deploy-application-infrastructure,
      build-and-push-react-artefacts,
    ]
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-react-app.yaml@v0.36
    with:
      environment: ${{ inputs.environment }}
      workspace: ${{ inputs.workspace }}
      domain: uec-cm
      artefact_sub_dir: ${{ inputs.workspace }}
      commit_hash: ${{ needs.metadata.outputs.commit_hash }}
      artefact_bucket_name: ${{ needs.metadata.outputs.artefact_bucket_name }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit
