name: Pipeline Deployment Application Test Environment

on:
  workflow_call:
    inputs:
      workspace:
        description: "The workspace to deploy the service into"
        required: true
        type: string
      tag:
        description: "Defines the tag to be used for deployment"
        required: true
        type: string

jobs:
  deploy-application-infrastructure:
    name: Deploy application infrastructure
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.23
    with:
      environment: test
      workspace: ${{ inputs.workspace }}
      domain: "uec-cm"
      project: cm
      stacks: "['application', 'ui-test']"
      tag: ${{ inputs.tag }}
      action: apply
    secrets: inherit

  build-and-deploy-react-app-to-s3-bucket:
    name: Build and deploy react app to S3 bucket
    needs: [
      deploy-application-infrastructure,
    ]
    uses: NHSDigital/uec-dos-management/.github/workflows/build-and-deploy-react-app.yaml@v0.23
    with:
      environment: test
      workspace: ${{ inputs.workspace }}
      domain: uec-cm
      tag: ${{ inputs.tag }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit
  ui-test:
    needs:
      [
        deploy-application-infrastructure,
        build-and-deploy-react-app-to-s3-bucket,
      ]
    name: Run ui tests
    uses: NHSDigital/uec-dos-management/.github/workflows/ui-test.yaml@v0.23
    with:
      environment: test
      workspace: ${{ inputs.workspace }}
      tag: ${{ inputs.tag }}
    secrets: inherit
