name: Pipeline Deployment Application Test Environment

# TODO add ref to use tag if necessary
# on:
#   push:
#     tags:
#       - '[A-Za-z][A-Za-z]-[0-9][0-9]?[0-9]?[0-9]?-[A-Za-z0-9][A-Za-z0-9]*-test'

on:
  workflow_call:
    inputs:
      git_tag:
        description: "Defines git commit tag to be used for deployment"
        required: true
        type: string
jobs:
  derive-tf-versions:
    name: Derive terraform version
    uses: ./.github/workflows/derive-tf-version.yaml
    with:
      git_ref: ${{ inputs.git_tag }}
  get-metadata:
    name: Get metadata
    runs-on: ubuntu-latest
    outputs:
      build_datetime: ${{ steps.metadata.outputs.build_datetime }}
      build_timestamp: ${{ steps.metadata.outputs.build_timestamp }}
      build_epoch: ${{ steps.metadata.outputs.build_epoch }}
    steps:
      - id: metadata
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "triggering action: ${{ github.event_name }}"
          echo "ref type: ${{ github.ref_type }}"
          echo "triggering git reference: ${{ github.ref_name }}"
          echo "deploying from git tag ${{ inputs.git_tag }}"
  deploy-application-infrastructure:
    name: Deploy application infrastructure
    needs:
      [
        derive-tf-versions,
      ]
    uses: ./.github/workflows/action-infrastructure-stack.yaml
    with:
      github_environment: "test"
      deployment_workspace: ${{ github.ref_name }}
      stack: temp
      action: plan
      tf_vers: ${{needs.derive-tf-versions.outputs.maxVersion}}
      git_ref: ${{ inputs.git_tag }}
    secrets: inherit
  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs:
      [
        get-metadata,
        deploy-application-infrastructure,
      ]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_tag }}
      - name: List Variables
        run: |
          export BUILD_DATETIME="${{ needs.get-metadata.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ needs.get-metadata.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ needs.get-metadata.outputs.build_epoch }}"
          echo "Integration tests invoked"
      # - name: Run Tests ...
      #   run: |
      #     ?
