name: Pipeline to Truncate Workflow History

on:
  push:
    branches:
      # - main
      - task/DR-644_Test_history_cleardown
#   # schedule:
#   #   - cron: '0 1 * * *'
#   # Run daily, at 01:00 .

jobs:


  delete_past_runs:
    name: "Remove older workflow runs"
    permissions:
      id-token: write
      contents: read
    uses: NHSDigital/uec-dos-management/.github/workflows/truncate-workflow-history.yaml@v0.45
    with:
      domain: "uec-cm"
      retain_days: 25
      minimum_history: 100
    secrets: inherit

  slack-notifications:
    needs: [
      delete_past_runs,
    ]
    if: always()
    uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@v0.45
    with:
      env: mgmt
    secrets: inherit
