name: Pipeline Deployment Application Prototype Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The name of the environment to build into"
        required: true
        default: 'prototype'
        type: string
      workspace:
        description: "The workspace to deploy the service into"
        required: true
        default: 'prototype'
        type: string

env:
  DOMAIN: uec-cm
  PROJECT: cm

jobs:
  set-environment-vars:
    name: "Set Environment Variables"
    runs-on: ubuntu-latest
    outputs:
      domain: ${{ env.DOMAIN }}
      project: ${{ env.PROJECT }}
    steps:
      - name: "Set Environment Variables"
        id: set-env
        run: echo "Set Environment Variables"

  metadata:
    name: "Get Metadata"
    needs:
      [
        set-environment-vars,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@latest

  deploy-application-infrastructure:
    name: "Deploy Application Infrastructure"
    needs: [
      metadata,
      set-environment-vars,
    ]
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@latest
    with:
      environment: ${{ inputs.environment }}
      domain: ${{ needs.set-environment-vars.outputs.domain }}
      project: ${{ needs.set-environment-vars.outputs.project }}
      workspace: ${{ inputs.workspace }}
      stacks: "['application']"
      action: apply
      workflow_timeout: 10
    secrets: inherit

  build-and-push-react-artefacts:
    name: "Build React Application and Push Artefact to S3 Bucket"
    needs: [
      set-environment-vars,
      metadata,
      deploy-application-infrastructure,
    ]
    uses: NHSDigital/uec-dos-management/.github/workflows/build-react-app.yaml@latest
    with:
      environment: ${{ inputs.environment }}
      workspace:  ${{ inputs.workspace }}
      domain: ${{ needs.set-environment-vars.outputs.domain }}
      commit_hash: ${{ needs.metadata.outputs.commit_hash }}
      artefact_bucket_name: ${{ needs.metadata.outputs.artefact_bucket_name }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  deploy-react-app:
    name: "Deploy React Application"
    needs: [
      set-environment-vars,
      metadata,
      deploy-application-infrastructure,
      build-and-push-react-artefacts,
    ]
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-react-app.yaml@latest
    with:
      environment: ${{ inputs.environment }}
      workspace: ${{ inputs.workspace }}
      domain: ${{ needs.set-environment-vars.outputs.domain }}
      artefact_sub_dir: ${{ inputs.workspace }}
      commit_hash: ${{ needs.metadata.outputs.commit_hash }}
      artefact_bucket_name: ${{ needs.metadata.outputs.artefact_bucket_name }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit
