name: Pipeline Deployment Application Test Environment

on:
  workflow_call:
    inputs:
      environment:
        description: "The name of the environment to build into"
        required: true
        type: string
      workspace:
        description: "The workspace to deploy the service into"
        required: true
        type: string
      # tag:
      #   description: "Defines the tag to be used for deployment"
      #   required: true
      #   type: string
      commit_hash:
        description: "The commit hash to identify the version of artefacts"
        required: true
        type: string
      artefact_bucket_name:
        description: "The name of domain repository for artefacts"
        required: true
        type: string

jobs:
  deploy-application-infrastructure:
    name: Deploy application infrastructure
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.35
    with:
      environment: ${{ inputs.environment }}
      domain: "uec-cm"
      project: cm
      workspace: ${{ inputs.workspace }}
      stacks: "['application']"
      # tag: ${{ inputs.tag }}
      action: apply
    secrets: inherit

  build-and-push-react-artefacts:
    name: Build react app and push built artefact to s3 bucket
    needs: [
      # metadata,
      deploy-application-infrastructure,
    ]
    uses: NHSDigital/uec-dos-management/.github/workflows/build-react-app.yaml@latest
    with:
      environment: ${{ inputs.environment }}
      workspace:  ${{ inputs.workspace }}
      domain: uec-cm
      commit_hash: ${{ inputs.commit_hash }}
      artefact_bucket_name: ${{ inputs.artefact_bucket_name }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  deploy-react-app:
    name: Retrieve built artefact and deploy to front end s3 bucket
    needs: [
      deploy-application-infrastructure,
    ]
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-react-app.yaml@v0.35
    with:
      environment: ${{ inputs.environment }}
      workspace: ${{ inputs.workspace }}
      domain: uec-cm
      # artefact_sub_dir:
      # code_directory:
      # tag: ${{ inputs.tag }}
      commit_hash: ${{ inputs.commit_hash }}
      artefact_bucket_name: ${{ inputs.artefact_bucket_name }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit
