name: Pipeline Cleardown Application Test Environment

on:
  pull_request:
    types:
      - closed

jobs:
  metadata:
    if: github.ref_type == 'branch' && startswith(github.head_ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    name: "Get Metadata"
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@latest
  destroy:
    if: github.ref_type == 'branch' && startswith(github.head_ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    uses: NHSDigital/uec-dos-management/.github/workflows/infrastructure-cleardown.yaml@latest
    needs:
      [
        metadata,
      ]
    with:
      environment: test
      workspace: ${{ needs.metadata.outputs.workspace }}
      project: cm
      domain: "uec-cm"
      stacks: '["application", "ui-test"]'
    secrets: inherit

  summarise:
    if: github.ref_type == 'branch' && startswith(github.head_ref, 'task/') && github.actor != 'github-merge-queue[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "${{ github.actor }} deleted a task branch..."
          echo "triggering cleardown of infra in test account relating to ${{ github.ref_type }}: ${{ github.event_ref }}"

  slack-notifications:
    name: Send notification to slack
    needs: [
      destroy,
      summarise,
    ]
    if: always()
    uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@latest
    with:
      env: test
    secrets: inherit
