name: Pipeline Deploy Account Level Infrastructure

on:
  push:
    branches:
      - 'main'

jobs:
    metadata:
      name: "Get Metadata"
      uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.23
    deploy-account-infrastructure-apply-dev:
      name: "Deploy Account Level Infrastructure to dev account"
      needs:
        [
          metadata,
        ]
      uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.23
      with:
        environment: dev
        domain: "uec-cm"
        project: cm
        workspace: ${{ needs.metadata.outputs.workspace }}
        stacks: '["terraform_management", "github-runner"]'
        action: apply
      secrets: inherit
    deploy-account-infrastructure-apply-test:
      name: "Deploy Account Level Infrastructure to test account"
      needs:
        [
          metadata,
        ]
      uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.23
      with:
        environment: test
        domain: "uec-cm"
        project: cm
        workspace: ${{ needs.metadata.outputs.workspace }}
        stacks: '["terraform_management", "github-runner"]'
        action: apply
      secrets: inherit
    slack-notifications:
      name: Send notification to slack
      needs: [
        metadata,
        deploy-account-infrastructure-apply-dev,
        deploy-account-infrastructure-apply-test,
      ]
      if: always()
      uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@v0.23
      with:
        env: dev
      secrets: inherit


