name: Tag and deploy code to integration account
on:
  pull_request:
    types: [ labeled ]

jobs:
  metadata:
    name: "Get Metadata"
    if: ${{ github.event.label.name == 'Int Ready' && startswith(github.head_ref, 'task/') }}
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@task/DR-644_Truncate_action_history
  generate-tag-name:
    name: "Generate Tag Name"
    needs:
      [
        metadata,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/generate-tag-name.yaml@task/DR-644_Truncate_action_history
    with:
      workspace: ${{ needs.metadata.outputs.workspace }}
      tag_type: int
      use_commit_hash: "yes"
      commit_hash: ${{ needs.metadata.outputs.artefact_commit_hash }}
  tag-repository:
    name: "Tag Repository"
    needs:
      [
        metadata,
        generate-tag-name,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/tag-repository.yaml@task/DR-644_Truncate_action_history
    with:
      tag_to_push: ${{ needs.generate-tag-name.outputs.tag_name }}
      tag_overwrite: "yes"
  deploy-to-int:
    name: Deploy to integration
    needs: [
      metadata,
      generate-tag-name,
      tag-repository,
    ]
    uses: ./.github/workflows/pipeline-deploy-app-int.yaml
    with:
      workspace: ${{ needs.metadata.outputs.workspace }}
      commit_hash: ${{ needs.metadata.outputs.artefact_commit_hash }}
    secrets: inherit
  slack-notifications:
    name: Send notification to slack
    needs: [
      metadata,
      generate-tag-name,
      tag-repository,
      deploy-to-int
    ]
    if: always()
    uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@task/DR-644_Truncate_action_history
    with:
      env: int
    secrets: inherit
