name: Tag code if PR labelled

on:
  pull_request:
    types: [ labeled ]

jobs:
  generate-test-ready-tag:
    # if: ${{ github.event.label.name == 'Test Ready' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Tag test ready code
        id: get-test-tag
        run: |
          export TAG_TYPE="T"
          echo "TEST_TAG=$(/bin/bash ./scripts/tag-code.sh)" >> $GITHUB_OUTPUT
    outputs:
      test_tag: "${{ steps.get-test-tag.outputs.TEST_TAG }}"
  apply-test-ready-tag:
    runs-on: ubuntu-latest
    needs: generate-test-ready-tag
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Tag test-ready code
        run: echo Tagging code with ${{needs.generate-test-ready-tag.outputs.test_tag}}

      - name: End
        run: echo Done

