name: Tag code if code labelled

on:
  pull_request:
    types: [ labeled ]

jobs:
  generate-test-ready-tag:
    if: ${{ github.event.label.name == 'Test Ready' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello ${{ github.event.label.name }}
  tag-code:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Tag test ready code
        run: |
          export ACTION=${{ inputs.action }}
          export STACK=${{ inputs.stack }}
          export ACCOUNT_TYPE=${{ vars.ACCOUNT_TYPE }}

          /bin/bash ./scripts/tag-code.sh
