name: Tag code if PR labelled

on:
  pull_request:
    types: [ labeled ]

jobs:
  generate-test-ready-tag:
    if: ${{ github.event.label.name == 'Test Ready' }} && startswith(github.head_ref, 'task/')
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch
        run: |
          echo "${{ github.head_ref  }}"
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate test ready tag
        id: get-test-tag
        run: |
          export TAG_TYPE="test"
          export BRANCH_NAME=${{ github.head_ref }}
          echo "TEST_TAG=$(/bin/bash ./scripts/tag-code.sh)" >> $GITHUB_OUTPUT
    outputs:
      test_tag: "${{ steps.get-test-tag.outputs.TEST_TAG }}"
  apply-test-ready-tag:
    runs-on: ubuntu-latest
    needs: generate-test-ready-tag
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Tag test ready code
        id: "tag-code"
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{needs.generate-test-ready-tag.outputs.test_tag}}
          tag_prefix: ""
  deploy-to-test:
    runs-on: ubuntu-latest
    needs: generate-test-ready-tag
    steps:
      - name: Deploy code to test environment
        uses: ./.github/workflows/pipeline-deploy-app-test.yaml



