name: Run ui tests

on:
  workflow_call:
    inputs:
      github_environment:
        description: "Defines the Github environment in which to pull environment variables from"
        required: true
        type: string
      deployment_workspace:
        description: 'Name of the terraform workspace to spin up the service infrastructure'
        required: false
        default: 'not-set'
        type: string
jobs:
  echo-workflow-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: echo workflow inputs
        run: |
          echo "github environment: ${{ inputs.github_environment }}"
          echo "deployment workspace: ${{ inputs.deployment_workspace }}"
  ui-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/uec-cm-github-runner
          role-session-name: github-pipeline-session
          aws-region: ${{ vars.AWS_REGION }}

      - name: set up node
        uses: actions/setup-node@v3
      - name: Install Allure command-line tool
        continue-on-error: true
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure_2.25.0-1_all.deb
          sudo dpkg -i allure_2.25.0-1_all.deb
          export PATH="$PATH:$(pwd)/allure_2.25.0-1/bin"
          allure --version

      - name: Run ui test script
        id: run-ui-tests-step
        run: |
          export BUILD_DATETIME="${{ inputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ inputs.build_timestamp }}"
          export BUILD_EPOCH="${{ inputs.build_epoch }}"
          export DEPLOYMENT_WORKSPACE=${{ inputs.deployment_workspace }}
          export ACCOUNT_TYPE=${{ inputs.github_environment }}
          echo "ui tests invoked"
          /bin/bash ./scripts/ui-tests.sh
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        id: test-artifact-upload-step
        with:
          name: allure-report
          path: tests/ui/allure-reports/index.html
          retention-days: 10
      - name: Upload accessibiity results
        if: always()
        uses: actions/upload-artifact@v4
        id: accessibiity-artifact-upload-step
        with:
          name: axe-report
          path: tests/ui/accessibility-reports/artifacts/*.html
          retention-days: 10
      - name: Check on failures
        if: steps.run-ui-tests-step.outcome != 'success'
        run: exit 1
